# Generated by Django 2.2.2 on 2019-07-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0002_resinlabel'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueType', models.CharField(max_length=10, verbose_name='问题类型')),
                ('issue', models.CharField(max_length=500, verbose_name='问题')),
                ('reason', models.CharField(max_length=500, verbose_name='原因')),
                ('solution', models.TextField(verbose_name='解决方案')),
            ],
        ),
        migrations.CreateModel(
            name='Issuelists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubtime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('Practiceissue', models.CharField(max_length=500, verbose_name='实际问题描述')),
                ('ColumnID', models.CharField(max_length=20, verbose_name='层柱析编号')),
                ('solutionMethod', models.TextField(verbose_name='实际解决问题方案')),
                ('issue', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='issuesmeter', to='issues.Issues', verbose_name='问题以及问题类型')),
                ('meterial', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='meterialsmete', to='material.ResinLabel', verbose_name='物料')),
            ],
        ),
    ]
