# Generated by Django 2.2.2 on 2019-06-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuelists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubtime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('Practiceissue', models.CharField(max_length=500, verbose_name='实际问题描述')),
                ('ColumnID', models.CharField(max_length=20, verbose_name='层柱析编号')),
                ('solutionMethod', models.TextField(verbose_name='实际解决问题方案')),
            ],
        ),
        migrations.AlterField(
            model_name='issues',
            name='issue',
            field=models.CharField(max_length=500, verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='reason',
            field=models.CharField(max_length=500, verbose_name='原因'),
        ),
        migrations.DeleteModel(
            name='MeterialIssues',
        ),
        migrations.AddField(
            model_name='issuelists',
            name='issue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='issuesmeter', to='issues.Issues', verbose_name='问题以及问题类型'),
        ),
    ]
