# Generated by Django 2.2.2 on 2019-06-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterialName', models.CharField(max_length=20)),
                ('meterialType', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('matrix', models.CharField(max_length=40)),
                ('ligand', models.CharField(max_length=10)),
                ('diameter', models.CharField(max_length=10)),
                ('tolePressure', models.CharField(blank=True, max_length=10)),
                ('phRange', models.CharField(blank=True, max_length=10)),
                ('storeMethod', models.CharField(blank=True, max_length=20)),
                ('comFactor', models.CharField(blank=True, max_length=10)),
                ('dbc', models.CharField(blank=True, max_length=10)),
                ('capacityRange', models.CharField(blank=True, max_length=10)),
                ('velocityPressure', models.CharField(blank=True, max_length=10)),
                ('validtyPeriod', models.CharField(blank=True, max_length=20)),
                ('packingMethod', models.CharField(blank=True, max_length=5)),
                ('packingdetail', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
