# Generated by Django 2.2.2 on 2019-07-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResinLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resinName', models.CharField(max_length=50, verbose_name='填料名称')),
                ('resinaType', models.CharField(max_length=50, verbose_name='填料类型')),
                ('brand', models.CharField(max_length=50, verbose_name='厂家')),
                ('matrix', models.CharField(max_length=50, verbose_name='基质')),
                ('ligand', models.CharField(max_length=50, verbose_name='功能基团')),
                ('diameter', models.CharField(max_length=10, verbose_name='粒径(um)')),
                ('Pmax', models.CharField(blank=True, max_length=10, verbose_name='耐受压力')),
                ('phRange', models.CharField(blank=True, max_length=10, verbose_name='PH范围')),
                ('storageMethod', models.CharField(blank=True, max_length=100, verbose_name='保存方法')),
                ('compactFactor', models.CharField(blank=True, max_length=10, verbose_name='压缩因子')),
                ('dbc', models.CharField(blank=True, max_length=10, verbose_name='DBC(mg/ml)')),
                ('LoadingRangeinProject', models.CharField(blank=True, max_length=10, verbose_name='项目生产载量范围')),
                ('PackingVmaxandPmax', models.CharField(blank=True, max_length=50, verbose_name='装柱最大流速压力')),
                ('expiry', models.CharField(blank=True, max_length=50, verbose_name='有效期')),
                ('TypeofColomuPackingMethod', models.CharField(blank=True, max_length=5, verbose_name='装柱方法类型')),
                ('ColomuPackingMethod', models.CharField(blank=True, max_length=1000, verbose_name='装柱方法')),
            ],
        ),
    ]
