# Generated by Django 2.2.2 on 2019-06-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20190622_1634'),
        ('columnstatictis', '0002_auto_20190622_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressureandvelocity',
            name='resin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materisesin', to='material.ResinLabel', verbose_name='填料id'),
        ),
    ]
